# Generated by Django 5.0.3 on 2024-03-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_allowance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 3, 25, 16, 32, 48, 815301)),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='female', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_deduction',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_earning',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(default='college', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra_allowance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='income_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(default='Gbeminiyi A.', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(default='single', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_premium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_deductions',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='professional_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(default='Python'),
        ),
    ]
