# Generated by Django 5.0.3 on 2024-03-25 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_alter_employee_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 3, 25, 21, 35, 36, 273763)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Female', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(default='College', max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(default='Single', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 21, 35, 36, 273763)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 21, 35, 36, 273763)),
        ),
    ]
