# Generated by Django 5.0.3 on 2024-03-25 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_employee_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 20, 47, 11, 439953, tzinfo=datetime.timezone.utc)),
        ),
    ]
