# Generated by Django 5.0.3 on 2024-03-27 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_employee_date_joined_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=500)),
                ('project_domain', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=300)),
                ('project_description', models.TextField(default='')),
                ('required_resources', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('project_manager', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 3, 27, 11, 54, 45, 855359, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 3, 27, 11, 54, 45, 855359, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 11, 54, 45, 854354, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.ManyToManyField(to='backend.employee'),
        ),
    ]
