# Generated by Django 5.0.3 on 2024-03-27 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_role',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 16, 20, 535469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 16, 20, 535996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 16, 20, 535996, tzinfo=datetime.timezone.utc)),
        ),
    ]
