# Generated by Django 5.0.3 on 2024-03-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_projects_project_role_alter_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefits',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 51, 7, 846432, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 51, 7, 846432, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_domain',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 12, 51, 7, 846432, tzinfo=datetime.timezone.utc)),
        ),
    ]
