# Generated by Django 5.0.3 on 2024-03-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_employeelogin_employee_role_employee_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLogin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
